---
  # set_hostname
  - name: setting up hostname
    import_role:
      name: hostname

  # write _domain to vars.
  - name: write _domain to vars
    lineinfile: 
      insertafter: EOF
      path: group_vars/linode/vars
      line: | 
        _domain: {{ _domain }}

  # set customer supplied sudo user, password and SSH keys
  - name: set sudo user
    user:
	      name: "{{ username }}"
        shell: /bin/bash
        groups: wheel
        password: "{{ password | password_hash('sha512') }}"
        update_password: on_create
        expires: -1
        append: yes
        generate_ssh_key: yes
        ssh_key_bits: 4096
        ssh_key_file: .ssh/id_rsa
        state: present
    when: username is defined

  # dns creation
  - name: create dns A record
    import_role:
      name: create_dns_record
    when: 
      - token_password is defined
      - default_dns is not defined

  # sets customer supplied ssh pubkey to limited user
  - name: set ssh pubkey
    import_role:
        name: sshkey
    when: 
      - pubkey is defined
      - username is defined

  # apt_setup_update
  - name: update system packages
    dnf:
      name: '*'
      state: latest        
    become: yes

  - name: import firewall rules 
    import_task:
      name: firewalld.yml

  - name: install nginx
    import_task:
      nginx.yml
  
  # ufw_install
  #- name: enabling ufw
  #  import_role:
  #    name: ufw

  # ufw rules 
  #- name: apply ufw rules
  #  import_tasks: ufw_rules.yml

  # fail2ban
  #- name: enabling fail2ban
  #  import_role:
  #    name: fail2ban_install

  # MainConcept  
  - name: Install packages
    yum:
      name: tar
      state: present

  - name: Install bzip2
    yum:
      name: bzip2
      state: present

  - name: Install wget
    yum:
      name: wget
      state: present