---
# set app specific ufw rules 
- name: Allow all access to tcp port 22
  community.general.ufw:
    rule: allow
    port: '22'
    proto: tcp


- name: Allow all access to the MC2GO tcp port
  community.general.ufw:
    rule: allow
    port: '{{mc2go_port}}'
    proto: tcp

