---
  - name: Set Download URL
    set_fact:
      mainconcept_url: "https://www.mainconcept.com/akamai-live-encoder"

  - name: Download MainConcept Live Encoder
    get_url:
      url: "{{ mainconcept_url }}"
      dest: "/tmp/MainConcept_Live_Encoder_Linux64_Setup_DEMO.tar.bz2"

  - name: Extract Installation
    unarchive:
      src: "/tmp/MainConcept_Live_Encoder_Linux64_Setup_DEMO.tar.bz2"
      dest: "/tmp/"  

  - name: Find .rpm files
    find:
      paths: /tmp/payload/
      patterns: "*.rpm"
    register: rpm_files  

  - name: Install MainConcept Live Encoder RPM
    command: "yum --nogpgcheck localinstall -y {{ item.path }}"
    loop: "{{ rpm_files.files }}"
    when: rpm_files.matched > 0
    args:
      chdir: /tmp/payload/

#  - name: Configure Firewall Ports 8080
#    shell: |
#      firewall-cmd --zone=public --add-port=8080/tcp --permanent
#
#  - name: Configure Firewall Ports 6000-6100
#    shell: |
#      firewall-cmd --zone=public --add-port=6000-6100/tcp --permanent
#
#  - name: Configure Firewall Ports 6000-6100
#    shell: |
#      firewall-cmd --reload


  - name: Add port 8080/tcp to the public zone
    ansible.builtin.firewalld:
      port: 8080/tcp
      permanent: yes
      state: enabled
    become: yes

  - name: Add ports 6000-6100/tcp to the public zone
    ansible.builtin.firewalld:
      port: 6000-6100/tcp
      permanent: yes
      state: enabled
    become: yes

  - name: Reload Firewall Configuration
    ansible.builtin.command: firewall-cmd --reload
    become: yes


  - name: Start MainConcept Live Encoder
    shell: /opt/McLiveEncoder/engine/run.sh &
    args:
      chdir: /opt/McLiveEncoder/engine/

