---
- name: create Docker volume for yacht_data
  docker_volume:
    name: yacht_data

- name: create Docker container for Yacht (with Compose support)
  docker_container:
    name: yacht
    image: selfhostedpro/yacht:latest
    state: started
    detach: yes
    ports:
      - "8000:8000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "yacht_data:/config"
      - "/opt/Yacht/compose:/compose"
    environment:
      COMPOSE_DIR: "/compose/"
      THEME: "{{ yacht_theme }}"
      ADMIN_EMAIL: "{{ yemail }}"
      ADMIN_PASSWORD: "{{ ypassword }}"
    when: compose_support == "Yes"

- name: create default compose directory and example project
  file:
    path: "/opt/Yacht/compose/example"
    state: directory
  when: compose_support == "Yes"

# templates/docker-compose.yml is grabbed from https://raw.githubusercontent.com/SelfhostedPro/selfhosted_templates/yacht/Template/Compose/example/docker-compose.yml
- name: add docker-compose.yml
  template:
    src: templates/docker-compose.yml
    dest: "/opt/Yacht/compose/example/docker-compose.yml"
  when: compose_support == "Yes"

- name: set MOTD message
  lineinfile:
    path: "/etc/update-motd.d/99-yacht"
    line: "The default compose directory is /opt/Yacht/compose.\nAn example project has been added there."
  when: compose_support == "Yes"

- name: create Docker container for Yacht (without Compose support)
  docker_container:
    name: yacht
    image: selfhostedpro/yacht:latest
    state: started
    detach: yes
    ports:
      - "8000:8000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "yacht_data:/config"
    environment:
      THEME: "{{ yacht_theme }}"
      ADMIN_EMAIL: "{{ yemail }}"
      ADMIN_PASSWORD: "{{ ypassword }}"
  when: compose_support == "No"

# Nginx
- name: install nginx
  apt:
    pkg:
      - nginx
    state: present

- name: config file setup
  template:
    src: templates/nginx.conf.j2
    dest: "/etc/nginx/sites-available/{{ _domain }}"      

- name: create a symbolic link for the nginx configuration
  file:
    src: "/etc/nginx/sites-available/{{ _domain }}"
    dest: "/etc/nginx/sites-enabled/{{ _domain }}"
    state: link

- name: unlink the default nginx configuration
  file:
    path: "/etc/nginx/sites-enabled/default"
    state: absent
  notify: reload nginx service

# ssl_certbot
- name: setting up ssl certificate
  import_role:
    name: certbot_ssl