---
# jupyter

- name: pull jupyter image
  docker_image:
    name: jupyter/minimal-notebook
    source: pull

- name: config file setup
  template:
    src: templates/jupyter.service
    dest: "/etc/systemd/system/jupyter.service"

- name: create docker compose directory
  file:
    path: /etc/docker/compose/jupyter
    state: directory

- name: docker file setup
  template:
    src: templates/docker-compose.yaml
    dest: "/etc/docker/compose/jupyter/docker-compose.yml"

- name: reload systemd daemon
  systemd:
    daemon_reload: yes

- name: enable jupyter service
  systemd:
    name: jupyter.service
    enabled: yes

- name: start jupyter service
  systemd:
    name: jupyter.service
    state: started

# nginx
- name: install nginx
  apt:
    pkg: nginx
    state: present

- name: config file setup
  template:
      src: templates/nginx.conf.j2
      dest: "/etc/nginx/sites-available/{{ _domain }}"  

- name: create a symbolic link for the nginx configuration
  file:
    src: "/etc/nginx/sites-available/{{ _domain }}"
    dest: "/etc/nginx/sites-enabled/{{ _domain }}"
    state: link

- name: unlink the default nginx configuration
  file:
    path: "/etc/nginx/sites-enabled/default"
    state: absent
  notify: reload nginx service

# ssl_certbot
- name: setting up ssl certificate
  import_role:
    name: certbot_ssl

# motd and creds gen
- name: copy MOTD template to /etc/motd
  template:
    src: templates/motd.j2
    dest: /etc/motd

- name: writing jupyter config into file
  copy:
    dest: /root/.jupyter/jupyter_lab_config.py
    mode: '0600'
    content: |
      c.ServerApp.root_dir = '/opt/notebooks'
      c.ServerApp.open_browser = False
      c.ServerApp.password = u'$HASHED_PASSWORD'
      c.ServerApp.allow_origin = '*'
      c.ServerApp.allow_root = True
      c.ServerApp.trust_xheaders = True