# linode ansible playbook

# linodes
- name: setting up environment 
  hosts: localhost
  connection: local
  any_errors_fatal: true
  user: root
  vars_files:
    - group_vars/linode/vars
  tasks:
    - name: install depend packages for openvpn
      apt:
        pkg:
        - ca-certificates
        - wget
        - net-tools
        - gnupg