---
- name: peppermint config and start
  block:
  - name: Configure service file 
    template:
      src: peppermint.service
      dest: "/etc/systemd/system/peppermint.service"

  - name: create docker compose directory
    file:
      path: /etc/docker/compose/peppermint/
      state: directory

  - name: create docker compose file
    template:
      src: docker-compose.yaml
      dest: "/etc/docker/compose/peppermint/docker-compose.yml"

  - name: get docker compose file
    replace:
      path: /etc/docker/compose/peppermint/docker-compose.yml
      regexp: 'localhost'
      replace: '{{ ansible_default_ipv4.address }}'

  - name: Reload systemd daemon
    systemd:
      daemon_reload: yes
      notify:
      - start peppermint service