# passbolt
- name: setting up environment 
  hosts: localhost
  connection: local
  any_errors_fatal: true
  user: root
  vars_files:
    - group_vars/linode/vars
  tasks:
  # generate creds
    - name: generating sudo user and password 
      import_tasks: ../linode_helpers/roles/sudouser/tasks/main.yml

    - name: writing gpg_key_passphrase to vars
      lineinfile:
        insertafter: EOF
        path: group_vars/linode/vars
        line: | 
          gpg_key_passphrase: {{ lookup('password', '/dev/null length=25 chars=ascii_letters,digits') }}

    - name: writing passbolt_db_admin_password to vars
      lineinfile:
        insertafter: EOF
        path: group_vars/linode/vars
        line: | 
          passbolt_db_admin_password: {{ lookup('password', '/dev/null length=25 chars=ascii_letters,digits') }}

    - name: writing passbolt_mysql_user to vars
      lineinfile:
        insertafter: EOF
        path: group_vars/linode/vars
        line: | 
          passbolt_mysql_user: passboltadmin

    - name: generating mysql root password
      import_tasks: ../linode_helpers/roles/securemysql/tasks/passgen.yml
