---
- name: create docker volume
  docker_volume:
    name: "uptime-kuma"

 # docker
- name: run postgres cocker container
  docker_container:
    name: uptime-kuma
    image: louislam/uptime-kuma:1
    restart_policy: always
    state: started
    volumes:
      - "uptime-kuma:/app/data"
    ports:
      - "3001:3001"

#Nginx setup

- name: nginx reverse setup
  block:
  - name: setup fqnd as default_dns
    set_fact:
      fqdn: "{{ default_dns }}"
    when: default_dns is defined

  - name: setup fqnd as subdomain.domain
    set_fact:
      fqdn: "{{ subdomain }}.{{ domain }}"
    when: subdomain is defined and domain is defined

  - name: install nginx
    apt:
      pkg:
      - nginx
      state: present

  - name: config file setup
    template:
      src: nginx.conf
      dest: "/etc/nginx/sites-available/{{ fqdn }}"    

  - name: create a symbolic link for the nginx configuration
    file:
      src: "/etc/nginx/sites-available/{{ fqdn }}"
      dest: "/etc/nginx/sites-enabled/{{ fqdn }}"
      state: link

  - name: nnlink the default nginx configuration
    file:
      path: "/etc/nginx/sites-enabled/default"
      state: absent

  - name: test nginx configuration
    command: nginx -t
    notify:
    - reload nginx service
