---
 # cloudron tasks as block
  - name: Install Cloudron, handle status 1, restart the Linode
    block:
    - name: download
      ansible.builtin.get_url: 
        url: https://cloudron.io/cloudron-setup 
        dest: /tmp/cloudron-setup 

    - name: move it 
      ansible.builtin.file: 
        path: /tmp/cloudron-setup
        mode: 754
    
    - name: run it
      ansible.builtin.command: 
        chdir: /tmp
        cmd: ./cloudron-setup --provider linode-mp
      register: result
    rescue: 
    - name: capture creds and restart the linode
      when: '"After reboot, visit one of the following URLs and accept the self-signed certificate to finish setup." in result.msg'
      debug: 
        msg: '{{ $result.msg }}'

    - name: reboot
      ansible.builtin.reboot: 
        reboot_timeout: 
