-
# motd and creds gen
- name: copy MOTD template to /etc/motd
  template:
    src: templates/motd.j2
    dest: /etc/motd

- name: writing passbolt creds into file
  copy:
    dest: /home/{{ username }}/.credentials
    mode: '0600'
    content: |
      Sudo Username: {{ username }}
      Sudo Password: {{ password }}
      Passbolt Admin Database User: passboltadmin
      Passbolt Database: passboltdb
      Passbolt Database Password: {{ passbolt_db_admin_password }}
      Mysql Root Password: {{ mysql_root_password }}
      Passbolt Login: admin
      Passbolt GPG Key Passphrase: {{ gpg_key_passphrase }}

- name: Copy passbolt config template to /etc/passbolt/passbolt.php
  template:
    src: templates/passbolt.php
    dest: /etc/passbolt/passbolt.php
    owner: www-data
    group: www-data
    mode: '0440'

- name: Create GPG key generation batch file with passphrase
  copy:
    dest: "/tmp/gpg_key_gen_batch"
    content: |
      %echo Generating a GPG key with a passphrase
      Key-Type: RSA
      Key-Length: 3072
      Subkey-Type: RSA
      Subkey-Length: 3072
      Name-Real: {{ passbolt_first_admin_username }}
      Name-Comment: Ansible generated key
      Name-Email: {{ passbolt_first_admin_email }}
      Expire-Date: 0
      Passphrase: {{ gpg_key_passphrase }}
      %commit
      %echo Done
  no_log: true

- name: Generate GPG key non-interactively with passphrase
  command: gpg --batch --generate-key /tmp/gpg_key_gen_batch
  environment:
    GNUPGHOME: /root/.gnupg

- name: Run gpg --list-secret-keys and save output to a temp file
  shell: gpg --list-secret-keys > /tmp/secret-keys.txt
  args:
    executable: /bin/bash

- name: Extract the key ID and save to a variable
  shell: |
    awk '/^sec/{getline; print $1}' /tmp/secret-keys.txt
  register: gpg_key_id_output

- name: Set the extracted key ID as a fact
  set_fact:
    gpg_secret_key: "{{ gpg_key_id_output.stdout }}"

- name: Display GPG secret key variable
  debug:
    msg: "The GPG secret key ID is: {{ gpg_secret_key }}"

- name: Writing gpg_secret_key to group_vars/linode/vars
  lineinfile:
    path: group_vars/linode/vars
    line: "gpg_secret_key: '{{ gpg_secret_key }}'"

- name: Update GPG fingerprint in passbolt.php
  ansible.builtin.replace:
    path: /etc/passbolt/passbolt.php
    regexp: "'fingerprint' => '.*',"
    replace: "'fingerprint' => '{{ gpg_secret_key }}',"

- name: Export GPG public key to serverkey.asc
  shell: >
    gpg --armor --export {{ gpg_secret_key }} > /etc/passbolt/gpg/serverkey.asc
  args:
    executable: /bin/bash

- name: Export GPG private key to serverkey_private.asc
  shell: >
    gpg --pinentry-mode loopback --passphrase "{{ gpg_key_passphrase }}" --armor --export-secret-keys {{ gpg_secret_key }} > /etc/passbolt/gpg/serverkey_private.asc
  args:
    executable: /bin/bash
  no_log: true

- name: Install Passbolt without admin user
  become: yes
  become_method: sudo
  become_user: "{{ webuser }}"
  shell: "/usr/share/php/passbolt/bin/cake passbolt install --no-admin --force"
  args:
    executable: /bin/bash

- name: Register first admin user for Passbolt
  become: yes
  become_method: sudo
  become_user: "{{ webuser }}"
  shell: "/usr/share/php/passbolt/bin/cake passbolt register_user -u {{ passbolt_first_admin_email }} -f {{ passbolt_first_admin_username }} -l {{ passbolt_first_admin_surname }} -r admin"
  args:
    executable: /bin/bash

- name: Set ownership and permissions for serverkey.asc
  ansible.builtin.file:
    path: /etc/passbolt/gpg/serverkey.asc
    owner: www-data
    group: www-data
    mode: '0440'  
    state: file

- name: Set ownership and permissions for serverkey_private.asc
  ansible.builtin.file:
    path: /etc/passbolt/gpg/serverkey_private.asc
    owner: www-data
    group: www-data
    mode: '0440'  
    state: file
