# linode ansible playbook

# linodes
- name: setting up environment 
  hosts: localhost
  connection: local
  any_errors_fatal: true
  user: root
  tasks:
    - name: generating sudo user and password 
      import_tasks: ../linode_helpers/roles/sudouser/tasks/main.yml

    - name: include post play
      import_playbook: post.yml
      vars:
        password: "{{ password }}"
