---
# set app specific ufw rules 
- name: Allow all access to tcp port 22
  community.general.ufw:
    rule: allow
    port: '22'
    proto: tcp

- name: Allow all access to nats server port
  community.general.ufw:
    rule: allow
    port: '4222'
    proto: tcp

- name: Allow all access to monitor port
  community.general.ufw:
    rule: allow
    port: '8222'
    proto: tcp

- name: Allow all access to mqtt port
  community.general.ufw:
    rule: allow
    port: '1883'
    proto: tcp
