---

- name: install required packages
  block:
    - name: netools install
      apt:
        pkg: net-tools
        state: present

    - name: curl install
      apt:
        pkg: curl 
        state: present

    - name: unzip install
      apt:
        pkg: unzip
        state: present

- name: create nats-server dir
  ansible.builtin.file:
    path: /tmp/nats-server
    state: directory

- name: Download and unzip nats server bin
  ansible.builtin.unarchive:
    src: https://github.com/nats-io/nats-server/releases/download/v{{ version }}/nats-server-v{{ version }}-linux-amd64.zip
    dest: /tmp/nats-server
    remote_src: yes

- name: Copy nats server bin to /bin
  ansible.builtin.copy:
    src: /tmp/nats-server/nats-server-v{{ version }}-linux-amd64/nats-server 
    dest: /usr/local/bin
    mode: '700'

- name: Add nats service file 
  template:
    src: nats.service.j2
    dest: "/etc/systemd/system/nats.service"

- name: Add nats config file 
  template:
    src: nats.conf.j2
    dest: "/etc/nats.conf"

- name: Reload systemd daemon
  systemd:
    daemon_reload: yes

- name: start nats service
  systemd:
    name: nats.service
    state: started
    enabled: yes

# motd
- name: copy MOTD template to /etc/motd
  template:
    src: templates/motd.j2
    dest: /etc/motd