---
# mysql
- name: installing mariadb
  apt:
    pkg:
    - mariadb-server
    - python3-mysqldb
    state: present
  register: mariadb

- name: running mysql secure installation
  import_role:
    name: securemysql

# php
- name: install php
  apt:
    pkg:
    - php-common
    - libapache2-mod-php
    - php-mysql
    state: present