---
 # apache
- name: installing apache
  apt:
    pkg:
    - apache2
    state: present

- name: enabling apache on boot
  service:
    name: apache2
    enabled: yes

- name: enable apache rewrite module
  apache2_module:
    name: rewrite
    state: present
  notify: restart apache2

- name: disable apache default site
  file:
    path: /etc/apache2/sites-enabled/000-default.conf
    state: absent

- name: moving vhost template
  template:
    src: templates/vhost.conf.j2
    dest: "/etc/apache2/sites-available/{{ _domain }}.conf"
    owner: root
    group: root
    mode: 0644

- name: symlinking our vhost
  file:
    src: "/etc/apache2/sites-available/{{ _domain }}.conf"
    dest: "/etc/apache2/sites-enabled/{{ _domain }}.conf"
    owner: root
    group: root
    mode: 0644
    state: link
  notify: restart apache2