- name: restart apache2
  systemd:
    name: apache2
    state: restarted
    enabled: yes

- name: restart zabbix-server 
  systemd: 
    name: zabbix-server
    state: restarted
    enable: yes

- name: restart zabbix-agent
  systemd: 
    name: zabbix-agent
    state: restarted
    enabled: yes