---
  # set_hostname
  - name: setting up hostname
    hostname:
    name: mc-ffmpeg-demo

  # set customer supplied sudo user, password and SSH keys
  - name: set sudo user
    import_role:
      name: sudouser
    when: username is defined

  # sets customer supplied ssh pubkey to limited user
  - name: set ssh pubkey
    import_role:
        name: sshkey
    when: 
      - pubkey is defined
      - username is defined

  # apt_setup_update
  - name: update system packages
    import_role:
      name: update_pkgs

  # ufw_install
  - name: enabling ufw
    import_role:
      name: ufw

  # ufw rules 
  - name: apply ufw rules
    import_tasks: ufw_rules.yml

  # fail2ban
  - name: enabling fail2ban
    import_role:
      name: fail2ban_install

  # MainConcept
  - name: Update and upgrade packages
    apt:
      update_cache: yes
      upgrade: dist

  - name: Install dependencies
    apt:
      name: "{{ item }}"
      state: present
    with_items:
      - tar
      - bzip2
      - wget
      - unzip

  - name: copy MOTD template to /etc/motd
    template:
    src: templates/motd.j2
    dest: /etc/motd     
