version: '3'
services:
  jupyterlab:
    image: jupyter/datascience-notebook:latest
    ports:
      - 127.0.0.1:8888:8888
    volumes:
      - ./notebooks:/home/jovyan/work
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_TOKEN=''
      - JUPYTER_NOTEBOOK_PASSWORD=${notebook_password}